feat: add expiration time
MapColonies/token-cli pull request #10
Opened 2022-05-09 12:11 UTC by asafMasa

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✖                                                                        |
| New feature     | ✔                                                                        |
| Breaking change | ✖                                                                        |
| Deprecations    | ✖                                                                        |
| Documentation   | ✖                                                                        |
| Tests added     | ✔                                                                        |
| Chore            | ✖                                                                       |

2022-05-09 12:42 UTC, cl-shaharshavit-rnd approved these changes

2022-05-11 08:55 UTC, CptSchnitz requested changes

2022-05-11 08:55 UTC, CptSchnitz commented on src/commands/generateToken.ts
> +  // https://github.com/panva/jose/blob/1a3d31c46756d4190ccc0cb9f35fa9861808ad60/src/jwt/produce.ts
adding some description in addition to the links would be nice (something like "the package expects a string describing duration, for example 2 weeks")

2022-05-11 08:55 UTC, CptSchnitz commented on src/commands/generateToken.ts
> +  yargs.option('t', { alias: 'ttl', type: 'string', description: '(optional) how much ttl from date.now' });
1. add to the description more information on how to specify the value.
2. no need to write optional, yargs adds it by itself to required (see image).
![image](https://user-images.githubusercontent.com/12687466/167810761-6a5e85a4-bf2d-4efe-9428-25d507a7c4d5.png)

2022-05-11 08:55 UTC, CptSchnitz commented on src/commands/generateToken.ts
> +    description: '(optional) the map-colonies domains the client will be allowed to access (raster, 3D, etc)',
remove optional.

2022-05-12 08:12 UTC, CptSchnitz requested changes

2022-05-12 08:12 UTC, CptSchnitz commented on src/commands/generateToken.ts
> +    description: 'how many TTL from date.now, the package will take the supplied time and add it to the time the token was generated',
add to the description like you added in the comment "for example '2h'"

2022-05-15 05:17 UTC, CptSchnitz approved these changes

2022-05-15 06:19 UTC, merged